image: ubuntu:latest

variables:
  PORT_CLIENT_ID: $PORT_CLIENT_ID
  PORT_CLIENT_SECRET: $PORT_CLIENT_SECRET
  DATADOG_API_KEY: $DATADOG_API_KEY
  DATADOG_APPLICATION_KEY: $DATADOG_APPLICATION_KEY
  DATADOG_ENVIRONMENT_ID: $DATADOG_ENVIRONMENT_ID

stages:
  - build

ingest_datadog_slo_to_port_job:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl jq
  script:
    - echo "Getting Datadog SLO"
    - sh datadog/start.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always